name: crawl answer

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

concurrency:
  group: crawl-group
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: 設定python環境
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: 安裝pip套件
        run: |
          pip install -r requirements.txt

      - name: 執行爬蟲
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          python -u main.py